name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Prepare Plugin
      #   run: | # modify this step as needed
      #     composer install --no-dev
      #     git add -f vendor

      - uses: kermage/action-wp-plugin-archiver@latest
        id: archive

      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.archive.outputs.plugin-zip }}
